from typing import Iterator, List, Optional

class Solver:
    def __init__(
        self, name: str = ..., bootstrap_with: Optional[List[List[int]]] = ...
    ) -> None: ...
    def __enter__(self) -> Solver: ...
    def __exit__(self, *ex: object) -> None: ...
    def delete(self) -> None: ...
    def solve(self) -> bool: ...
    def enum_models(self) -> Iterator[List[int]]: ...
    def get_model(self) -> List[int]: ...
